# Board Setup
esp8266:
  board: esp01_1m

binary_sensor:
  - id: !extend doorman_boot_button
    pin:
      ignore_strapping_warning: !remove

# TODO: Proper GPIO selection
tc_bus:
  rx_pin: 12
  tx_pin: 13

substitutions:
  led_pin: "GPIO2"
  rgb_led_pin: "" # use dummy light
  relay_pin: "GPIO14"
  external_button_pin: "GPIO15"
  adc_input_pin: "A0"