# Board Setup
esp8266:
  board: esp01_1m
  framework:
    type: arduino
    version: recommended

# Incompatible with RMT light
# TODO: implement specific light

# Incompatible with debug free psram

# TODO
substitutions:
  led_pin: "GPIO1"
  rgb_led_pin: "GPIO2"
  relay_pin: "GPIO42"
  external_button_pin: "GPIO41"