# Doorman S3 Firmware
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"

# Import Doorman Stock Firmware Config
packages:
  AzonInc.Doorman: github://azoninc/doorman/firmware/ha-doorman-stock.yaml@master

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password