# Doorman Standard Firmware (Custom)
# Base Board DOORMAN-S3-REV2

# You can change a few options here.
substitutions:
  name: "doorman-s3-local-dev"
  friendly_name: "Doorman S3 (Development)"
  branch: "local"
  firmware_type: "standard"
  api_variant: "custom"
  host_platform: "doorman-s3-rev2"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false
  project:
    name: AzonInc.Doorman Standard
    version: 2026.3.0

wifi:
  id: wifi_id
  ap:
    ssid: "${friendly_name} Setup"
    password: "Op3n-Sesame!"

captive_portal:

improv_serial:

packages:
  host: !include ../packages/host/doorman-s3-rev2.yaml
  external_components: !include ../packages/common/external-components.local.yaml
  rgb_status_led: !include ../packages/common/rgb-status-led.sk6812b.yaml
  rgb_status_led_effects: !include ../packages/common/rgb-status-led.effects.yaml
  base: !include ../packages/common/base.yaml
  webserver_dev: !include ../packages/common/web-server.dev.yaml
  ota_update_esphome: !include ../packages/ota/esphome.yaml
  api: !include ../packages/api/custom.yaml
  debug_utilities: !include ../packages/debug/debug-utilities.yaml
  debug_component: !include ../packages/debug/debug-component.yaml
  debug_component_psram: !include ../packages/debug/debug-component.psram.yaml
  virtual_devices: !include ../packages/bus_devices/virtual-devices.yaml
  pattern_events: !include ../packages/pattern_events/pattern-events.yaml
  ring_to_open: !include ../packages/ring_to_open/ring-to-open.yaml
  indoor_station_settings: !include ../packages/bus_devices/indoor-station-settings.yaml
  interactive_setup: !include ../packages/bus_devices/interactive-setup.yaml
  outdoor_station: !include ../packages/bus_devices/outdoor-station.yaml