# Doorman Nuki Bridge Firmware (HomeKit)
# Base Board DOORMAN-S3-REV2

# ESPHome Dashboard import and remote logging are not
# supported in this firmware, as they require the API.
# Available only via the Home Assistant API integration.

# You can change a few options here.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  ap_password: "Op3n-Sesame!"
  # DO NOT CHANGE - INTERNALLY USED
  branch: "dev"
  firmware_type: "nuki-bridge"
  api_variant: "homekit"
  host_platform: "doorman-s3-rev2"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  remote_package_files:
    url: https://github.com/azoninc/doorman
    ref: dev
    refresh: 0s
    files:
      - path: firmware/packages/host/doorman-s3-rev2.yaml
      - path: firmware/packages/common/rgb-status-led.sk6812b.yaml
      - path: firmware/packages/common/rgb-status-led.effects.yaml
      - path: firmware/packages/common/external-components.yaml
      - path: firmware/packages/common/base.yaml
      - path: firmware/packages/common/wifi.yaml
      - path: firmware/packages/ota/esphome.yaml
      - path: firmware/packages/api/homekit.yaml
      - path: firmware/packages/debug/debug-utilities.yaml
      - path: firmware/packages/debug/debug-component.yaml
      - path: firmware/packages/debug/debug-component.psram.yaml
      - path: firmware/packages/pattern_events/pattern-events.yaml
      - path: firmware/packages/ring_to_open/ring-to-open.yaml
      - path: firmware/packages/ring_to_open/ring-to-open.homekit.yaml
      - path: firmware/packages/ring_to_open/ring-to-open-nuki.yaml
      - path: firmware/packages/bus_devices/indoor-station-settings.yaml
      - path: firmware/packages/nuki/nuki-bridge.yaml
      - path: firmware/packages/bus_devices/interactive-setup.yaml