# Doorman Standard Firmware (HomeKit)
# Base Board DOORMAN-S3

# ESPHome Dashboard import and remote logging are not
# supported in this firmware, as they require the API.
# Available only via the Home Assistant API integration.

# You can change a few options here.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  ap_password: "Op3n-Sesame!"
  # DO NOT CHANGE - INTERNALLY USED
  branch: "dev"
  firmware_type: "standard"
  api_variant: "homekit"
  host_platform: "doorman-s3"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

packages:
  host: !include ../packages/host/${host_platform}.yaml
  rgb_status_led: !include ../packages/common/rgb-status-led.yaml
  solid_state_relay: !include ../packages/common/relay.yaml
  external_components: !include ../packages/common/external-components.yaml
  base: !include ../packages/common/base.yaml
  wifi: !include ../packages/common/wifi.yaml
  wifi_psram: !include ../packages/common/wifi.psram.yaml
  ota_update_esphome: !include ../packages/ota/esphome.yaml
  ota_update_http: !include ../packages/ota/http.yaml
  api: !include ../packages/api/homekit.yaml
  bluedroid_ble: !include ../packages/common/bluedroid-ble.yaml
  bluedroid_ble_psram: !include ../packages/common/bluedroid-ble.psram.yaml
  debug_utilities: !include ../packages/debug/debug-utilities.yaml
  pattern_events: !include ../packages/pattern_events/pattern-events.yaml
  ring_to_open: !include ../packages/ring_to_open/ring-to-open.yaml
  ring_to_open_homekit: !include ../packages/ring_to_open/ring-to-open.homekit.yaml
  indoor_station_settings: !include ../packages/bus_devices/indoor-station-settings.yaml
  interactive_setup: !include ../packages/bus_devices/interactive-setup.yaml