# Doorman Nuki Bridge Firmware (Home Assistant)
# Base Board DOORMAN-S3-REV2-AUDIO

# You can change a few options here.
substitutions:
  name: "doorman-s3-local-dev"
  friendly_name: "Doorman S3 (Development)"
  ap_password: "Op3n-Sesame!"
  # DO NOT CHANGE - INTERNALLY USED
  branch: "local"
  firmware_type: "nuki-bridge"
  api_variant: "ha"
  host_platform: "doorman-s3-rev2-audio"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  host: !include ../packages/host/${host_platform}.yaml
  rgb_status_led: !include ../packages/common/rgb-status-led.yaml
  solid_state_relay: !include ../packages/common/relay.yaml
  extension_board: !include ../packages/extension_boards/common.yaml
  extension_board_audio: !include ../packages/extension_boards/audio.yaml
  external_components: !include ../packages/common/external-components.local.yaml
  base: !include ../packages/common/base.yaml
  wifi: !include ../packages/common/wifi.yaml
  wifi_psram: !include ../packages/common/wifi.psram.yaml
  ota_esphome: !include ../packages/ota/esphome.yaml
  api: !include ../packages/api/homeassistant.yaml
  debug_utilities: !include ../packages/debug/debug-utilities.yaml
  debug_component: !include ../packages/debug/debug-component.yaml
  pattern_events: !include ../packages/pattern_events/pattern-events.yaml
  ring_to_open: !include ../packages/ring_to_open/ring-to-open.yaml
  ring_to_open_nuki: !include ../packages/ring_to_open/ring-to-open-nuki.yaml
  indoor_station_settings: !include ../packages/bus_devices/indoor-station-settings.yaml
  addon_nuki_bridge: !include ../packages/nuki/nuki-bridge.yaml
  interactive_setup: !include ../packages/bus_devices/interactive-setup.yaml
  virtual_indoor_station: !include ../packages/bus_devices/virtual-indoor-station.yaml