substitutions:
  branch: "local"
  firmware_type: "nuki-bridge"
  api_variant: "ha"
  host_platform: "doorman-s3-rev2"

packages:
  host: !include ../hosts/doorman-s3-rev2.yaml
  external_components_local: !include ../components/external-components.local.yaml
  rgb_status_led: !include ../components/rgb-status-led.sk6812b.yaml
  rgb_status_led_effects: !include ../components/rgb-status-led.effects.yaml
  base: !include ../base.yaml
  webserver_dev: !include ../components/web-server.dev.yaml
  ota_update_esphome: !include ../components/ota-update.esphome.yaml
  api: !include ../components/api.homeassistant.yaml
  debug_utilities: !include ../components/debug-utilities.yaml
  debug_component: !include ../components/debug-component.yaml
  debug_component_psram: !include ../components/debug-component.psram.yaml
  virtual_devices: !include ../components/virtual-devices.yaml
  pattern_events: !include ../components/pattern-events.yaml
  ring_to_open: !include ../components/ring-to-open.yaml
  ring_to_open_nuki: !include ../components/ring-to-open-nuki.yaml
  indoor_station_settings: !include ../components/indoor-station-settings.yaml
  addon_nuki_bridge: !include ../components/nuki-bridge.yaml
  interactive_setup: !include ../components/interactive-setup.yaml
  outdoor_station: !include ../components/outdoor-station.yaml