# Doorman Standard Firmware (Custom)
# Base Board DOORMAN-S3-REV2-AUDIO

# ESPHome Dashboard import and remote logging are not
# supported in this firmware, as they require the API.
# Available only via the Home Assistant API integration.

# You can change a few options here.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  ap_password: "Op3n-Sesame!"
  # DO NOT CHANGE - INTERNALLY USED
  branch: "master"
  firmware_type: "standard"
  api_variant: "custom"
  host_platform: "doorman-s3-rev2-audio"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  remote_package_files:
    url: https://github.com/azoninc/doorman
    ref: master
    refresh: 0s
    files:
      - path: firmware/packages/host/doorman-s3-rev2-audio.yaml
      - path: firmware/packages/common/rgb-status-led.ws2812b.yaml
      - path: firmware/packages/common/rgb-status-led.effects.yaml
      - path: firmware/packages/common/external-components.yaml
      - path: firmware/packages/common/base.yaml
      - path: firmware/packages/common/wifi.yaml
      - path: firmware/packages/audio/es8311.yaml
      - path: firmware/packages/ota/esphome.yaml
      - path: firmware/packages/api/custom.yaml
      - path: firmware/packages/pattern_events/pattern-events.yaml
      - path: firmware/packages/ring_to_open/ring-to-open.yaml
      - path: firmware/packages/bus_devices/indoor-station-settings.yaml
      - path: firmware/packages/bus_devices/interactive-setup.yaml