# Doorman Nuki Bridge Firmware (Home Assistant)
# Base Board ESP32-S3-QUAD

# You can change a few options here.
substitutions:
  name: "doorman-s3-local-dev"
  friendly_name: "Doorman S3 (Development)"
  branch: "local"
  firmware_type: "nuki-bridge"
  api_variant: "ha"
  host_platform: "esp32-s3-quad"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false
  project:
    name: AzonInc.Doorman Nuki-Bridge
    version: 2026.3.0

wifi:
  id: wifi_id
  ap:
    ssid: "${friendly_name} Setup"
    password: "Op3n-Sesame!"

captive_portal:

improv_serial:

packages:
  host: !include ../packages/host/esp32-s3-quad.yaml
  external_components: !include ../packages/common/external-components.local.yaml
  rgb_status_led: !include ../packages/common/rgb-status-led.ws2812b.yaml
  rgb_status_led_effects: !include ../packages/common/rgb-status-led.effects.yaml
  base: !include ../packages/common/base.yaml
  webserver_dev: !include ../packages/common/web-server.dev.yaml
  ota_update_esphome: !include ../packages/ota/esphome.yaml
  api: !include ../packages/api/homeassistant.yaml
  debug_utilities: !include ../packages/debug/debug-utilities.yaml
  debug_component: !include ../packages/debug/debug-component.yaml
  debug_component_psram: !include ../packages/debug/debug-component.psram.yaml
  virtual_devices: !include ../packages/bus_devices/virtual-devices.yaml
  pattern_events: !include ../packages/pattern_events/pattern-events.yaml
  ring_to_open: !include ../packages/ring_to_open/ring-to-open.yaml
  ring_to_open_nuki: !include ../packages/ring_to_open/ring-to-open-nuki.yaml
  indoor_station_settings: !include ../packages/bus_devices/indoor-station-settings.yaml
  addon_nuki_bridge: !include ../packages/nuki/nuki-bridge.yaml
  interactive_setup: !include ../packages/bus_devices/interactive-setup.yaml
  outdoor_station: !include ../packages/bus_devices/outdoor-station.yaml