substitutions:
  branch: "master"
  firmware_type: "nuki-bridge"
  api_variant: "ha"
  host_platform: "esp32-s3-oct"

packages:
  host: !include ../hosts/esp32-s3-oct.yaml
  rgb_status_led: !include ../components/rgb-status-led.yaml
  base: !include ../base.yaml
  ota_updates: !include ../components/ota-updates.yaml
  dashboard_import: !include ../components/dashboard-import.yaml
  homeassistant: !include ../components/homeassistant.yaml
  pattern_events: !include ../components/pattern-events.yaml
  ring_to_open: !include ../components/ring-to-open.yaml
  intercom_settings: !include ../components/intercom-settings.yaml
  addon_nuki_bridge: !include ../components/nuki-bridge.yaml
  interactive_setup: !include ../components/interactive-setup.yaml