# Doorman Standard Firmware (Home Assistant)
# Base Board ESP32-S3

# You can change a few options here.
substitutions:
  name: "doorman-s3-local-dev"
  friendly_name: "Doorman S3 (Development)"
  # led_pin: "GPIO1"
  # rgb_led_pin: "GPIO2"
  # relay_pin: "GPIO42"
  # external_button_pin: "GPIO41"
  # adc_input_pin: "GPIO10"

# Import Doorman Firmware Config
packages:
  AzonInc.Doorman-Standard: !include ../configurations/esp32-s3.ha.standard.local.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - platform: tc_bus
    id: internal_call_sensor
    name: "Internal Call ISH3030"
    type: internal_call
    address: 255
    payload: 255
    serial_number: 798906
    auto_off: 2s
    on_press:
      - tc_bus.send:
          type: ack_status
          payload: 0x1

      - delay: 2s

      - tc_bus.send:
          type: start_talking
          serial_number: 798906
          address: 63

  - platform: tc_bus
    id: start_talking_sensor
    name: "Start Talking ISW5010"
    type: start_talking
    address: 12
    payload: 1
    serial_number: 398149
    auto_off: 2s
    on_press:
      - tc_bus.send:
          type: ack_status
          payload: 0x1

button:
  - platform: template
    name: "Internal Call ISW5010"
    on_press:
      - tc_bus.send:
          type: internal_call
          serial_number: 398149
          address: 12
          #0613457F