# Doorman Stock Firmware (MQTT)
# Base Board ESP8266

# You can change a few options here.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  # log_level: "ERROR"
  # led_pin: "GPIO1"
  # rgb_led_pin: "GPIO2"
  # relay_pin: "GPIO42"
  # external_button_pin: "GPIO41"

# Import Doorman Firmware Config
packages:
  AzonInc.Doorman: github://azoninc/doorman/firmware/esp8266.mqtt.stock.yaml@master

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password