# Doorman S3 Stock Firmware
# Example Configuration to use Events & Doorbell Button Patterns


# The following Entities are already preconfigured:
# - Entrance Doorbell Sensor
# - Apartment Doorbell Sensor
# - Door Opener Button
# - Party Mode Switch (Disabled by default)
# - Last Bus Command (Disabled by default)
# - External Button (Disabled by default)
# - Relay (Disabled by default)


# You can change a few options here.
# There are more substitutions available for testing - just take a look at Github.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"

  # TCS Commands
  # Make sure to change all commands to yours in order to use the preconfigured Entities
  apartment_doorbell_command: "0x00000000"
  entrance_doorbell_command: "0x00000000"
  entrance_door_opener_command: "0x1100"

  # Optional Settings
  # log_level: "ERROR"
  # party_mode_door_opener_delay: "70ms"


# Import Doorman Stock Firmware Config
packages:
  AzonInc.Doorman_S3: github://AzonInc/doorman/firmware/doorman-stock.yaml@master


esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: "REPLACEME"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password



# Define some events here
event:
  - platform: template
    id: doorbell_pattern
    name: "Doorbell Pattern"
    device_class: DOORBELL
    event_types:
      - "apartment_single"
      - "apartment_double"
      - "apartment_triple"
      - "entrance_single"
      - "entrance_double"
      - "entrance_triple"


# Homeassistant Automation Trigger Example
# Change the Event Entity ID to your Doorman S3 Doorbell Pattern Event Entity

#trigger:
#  - platform: state
#    entity_id:
#      - event.doorman_s3_doorbell_pattern
#    attribute: event_type
#    to: entrance_triple



# Define Button Patterns here that trigger the events above
binary_sensor:
  - platform: tcs_intercom
    command: ${entrance_doorbell_command}
    auto_off: 0.5s
    internal: true
    # Single press
    on_press:
      - event.trigger:
          id: doorbell_pattern
          event_type: entrance_single
    on_multi_click:
      # Double press
      - timing:
          - ON for at most 1s
          - OFF for at most 1s

          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: entrance_double
      # Triple press
      - timing:
          - ON for at most 1s
          - OFF for at most 1s

          - ON for at most 1s
          - OFF for at most 1s

          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: entrance_triple

  - platform: tcs_intercom
    command: ${apartment_doorbell_command}
    auto_off: 0.5s
    internal: true
    # Single press
    on_press:
      - event.trigger:
          id: doorbell_pattern
          event_type: apartment_single
    on_multi_click:
      # Double press
      - timing:
          - ON for at most 1s
          - OFF for at most 1s

          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: apartment_double
      # Triple press
      - timing:
          - ON for at most 1s
          - OFF for at most 1s

          - ON for at most 1s
          - OFF for at most 1s

          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: apartment_triple