esp32:
  framework:
    type: arduino
    version: 2.0.16
    platform_version: 6.7.0

esphome:
  libraries:
  - Preferences
  - https://github.com/h2zero/NimBLE-Arduino#1.4.0
  - Crc16
  - https://github.com/AzonInc/NukiBleEsp32

external_components:
  - source: github://AzonInc/ESPHome_nuki_lock@main

# Pairing Mode
binary_sensor:
  - id: !extend doorman_boot_button
    on_multi_click:
      - timing:
            - ON for at least 5s
        then:
          - if:
              condition:
                binary_sensor.is_on: nuki_paired
              then:
                - nuki_lock.unpair:
                    id: nuki_smart_lock
                - lambda: |
                    ESP_LOGI("pairing", "Pairing Mode: TODO");
            
          - nuki_lock.set_pairing_mode: 
              id: nuki_smart_lock
              pairing_mode: true


# Nuki Lock Bridge
lock:
  - platform: nuki_lock
    name: Nuki Lock
    id: nuki_smart_lock

    # Required:
    is_connected: 
      id: nuki_connected
      name: "Nuki Connected"
      icon: "mdi:link"
      entity_category: DIAGNOSTIC
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: -10

    is_paired:
      id: nuki_paired
      name: "Nuki Paired"
      icon: "mdi:link"
      entity_category: DIAGNOSTIC
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: -9

    # Optional:
    battery_critical:
      id: nuki_battery_critical
      name: "Nuki Battery Critical"
      entity_category: DIAGNOSTIC
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: -8

    battery_level:
      id: nuki_battery_level
      name: "Nuki Battery Level"
      entity_category: DIAGNOSTIC
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: -7

    door_sensor:
      id: nuki_door_sensor
      name: "Nuki Door Sensor"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: -6

    door_sensor_state:
      id: nuki_door_sensor_state
      name: "Nuki Door Sensor State"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: -5

    pairing_mode:
      id: nuki_pairing_mode
      name: "Nuki Pairing Mode"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: -4

    unpair:
      id: nuki_unpair_device
      name: "Nuki Unpair Device"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_nuki
        sorting_weight: -3

    on_pairing_mode_on_action:
      - script.execute: update_led

    on_pairing_mode_off_action:
      - script.execute: update_led
    
    on_paired_action:
      - light.turn_on:
          id: doorman_rgb_status_led
          red: 100%
          green: 0%
          blue: 100%
          effect: none
          brightness: 60%
      - delay: 3s
      - script.execute: update_led

    web_server:
      sorting_group_id: sorting_group_nuki
      sorting_weight: -11

script:
  - id: !extend update_led
    then:
      - if:
          condition:
            - switch.is_on: nuki_pairing_mode
          then:
            - light.turn_on:
                id: doorman_rgb_status_led
                red: 100%
                green: 0%
                blue: 100%
                effect: pulse
