esphome:
  libraries:
  - Preferences
  - https://github.com/h2zero/NimBLE-Arduino
  - https://github.com/vinmenn/Crc16
  - https://github.com/AzonInc/NukiBleEsp32

external_components:
  - source: github://AzonInc/ESPHome_nuki_lock@main

# Pairing Mode
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
      ignore_strapping_warning: true
    internal: true
    id: doorman_boot_button
    on_multi_click:
      - timing:
            - ON for at least 5s
        then:
          - if:
              condition:
                binary_sensor.is_on: nuki_paired
              then:
                - nuki_lock.unpair:
                    id: nuki_smart_lock
                - lambda: |
                    ESP_LOGI("pairing", "Pairing Mode: TODO");
            
          - nuki_lock.set_pairing_mode: 
              id: nuki_smart_lock
              pairing_mode: true