# Pattern Events Addon

event:
  - platform: template
    id: doorbell_pattern
    name: "Doorbell Pattern"
    icon: "mdi:doorbell"
    device_class: DOORBELL
    event_types:
      - "apartment_single"
      - "apartment_double"
      - "apartment_triple"
      - "entrance_single"
      - "entrance_double"
      - "entrance_triple"
      - "second_entrance_single"
      - "second_entrance_double"
      - "second_entrance_triple"

  - platform: template
    id: phone_pick_up_pattern
    name: "Phone pick up Pattern"
    icon: "mdi:phone-incoming-outgoing"
    event_types:
      - "single"
      - "double"
      - "triple"

binary_sensor:
  - id: !extend entrance_doorbell
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: entrance_single

      # Double press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: entrance_double
              
      # Triple press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: entrance_triple


  - id: !extend second_entrance_doorbell
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: second_entrance_single

      # Double press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: second_entrance_double
              
      # Triple press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: second_entrance_triple


  - id: !extend apartment_doorbell
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: apartment_single

      # Double press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: apartment_double
              
      # Triple press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: doorbell_pattern
              event_type: apartment_triple


  - id: !extend pick_up_phone
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: phone_pick_up_pattern
              event_type: single

      # Double press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: phone_pick_up_pattern
              event_type: double
              
      # Triple press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: phone_pick_up_pattern
              event_type: triple