# Pattern Events Addon

event:
  - platform: template
    id: entrance_doorbell_pattern
    name: "Entrance Doorbell"
    icon: "mdi:doorbell"
    device_class: DOORBELL
    event_types:
      - "single"
      - "double"
      - "triple"
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -30

  - platform: template
    id: second_entrance_doorbell_pattern
    name: "Second Entrance Doorbell"
    icon: "mdi:doorbell"
    device_class: DOORBELL
    event_types:
      - "single"
      - "double"
      - "triple"
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -40

  - platform: template
    id: apartment_doorbell_pattern
    name: "Apartment Doorbell"
    icon: "mdi:doorbell"
    device_class: DOORBELL
    event_types:
      - "single"
      - "double"
      - "triple"
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -50

  - platform: template
    id: phone_pick_up_pattern
    name: "Phone pick up Pattern"
    icon: "mdi:phone-incoming-outgoing"
    event_types:
      - "single"
      - "double"
      - "triple"
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -20

binary_sensor:
  - id: !extend entrance_doorbell
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: entrance_doorbell_pattern
              event_type: single

      # Double press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: entrance_doorbell_pattern
              event_type: double
              
      # Triple press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: entrance_doorbell_pattern
              event_type: triple


  - id: !extend second_entrance_doorbell
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: second_entrance_doorbell_pattern
              event_type: single

      # Double press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: second_entrance_doorbell_pattern
              event_type: double
              
      # Triple press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: second_entrance_doorbell_pattern
              event_type: triple


  - id: !extend apartment_doorbell
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: apartment_doorbell_pattern
              event_type: single

      # Double press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: apartment_doorbell_pattern
              event_type: double
              
      # Triple press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: apartment_doorbell_pattern
              event_type: triple


  - id: !extend pick_up_phone
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: phone_pick_up_pattern
              event_type: single

      # Double press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: phone_pick_up_pattern
              event_type: double
              
      # Triple press
      - timing:
          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at most 1s

          - ON for at most 0.5s
          - OFF for at least 2s
        then:
          - event.trigger:
              id: phone_pick_up_pattern
              event_type: triple
