tc_bus_device:
  - id: virtual_indoor_station
    type: indoor_station
    virtual: true
    on_incoming_call:
      - logger.log: INCOMING CALL FROM AS / IA
    on_call_started:
      - logger.log: CALL STARTED, AUDIO MODE
    on_call_ended:
      - logger.log: CALL ENDED
    on_call_failed:
      - logger.log: CALL FAILED

  - id: virtual_outdoor_station
    type: outdoor_station
    virtual: true
    on_incoming_call:
      - logger.log: INCOMING CALL FROM IS
    on_call_started:
      - logger.log: CALL STARTED, AUDIO MODE
    on_call_ended:
      - logger.log: CALL ENDED
    on_call_failed:
      - logger.log: CALL FAILED


binary_sensor:
  - platform: tc_bus_device
    tc_bus_device_id: virtual_outdoor_station
    sensor_type: door_opener
    id: door_opener_active
    name: "Door Opener Active"
    on_press:
      - logger.log: Turn on door opener
    on_release:
      - logger.log: Turn off door opener


number:
  - platform: tc_bus_device
    tc_bus_device_id: virtual_indoor_station
    serial_number:
      id: virtual_indoor_station_serial_number
      name: "Virtual IS Serial Number"

  - platform: tc_bus_device
    tc_bus_device_id: virtual_outdoor_station
    serial_number:
      id: virtual_outdoor_station_serial_number
      name: "Virtual AS Serial Number"
    address:
      id: virtual_outdoor_station_address
      name: "Virtual AS Address"

button:
  - platform: template
    name: "Answer Call ON VIS"
    on_press:
      - tc_bus_device.answer_call:
          id: virtual_indoor_station

  - platform: template
    name: "End Call ON VIS"
    on_press:
      - tc_bus_device.end_call:
          id: virtual_indoor_station

  - platform: template
    name: "End Call ON VAS"
    on_press:
      - tc_bus_device.end_call:
          id: virtual_outdoor_station

  - platform: template
    name: "Call ISW5030 ON VIS"
    on_press:
      - tc_bus_device.call:
          id: virtual_indoor_station
          address: 398149
          internal: true

  - platform: template
    name: "Call ISW5030 ON VAS"
    on_press:
      - tc_bus_device.call:
          id: virtual_outdoor_station
          address: 398149

  - platform: template
    name: "Talk to AS 0 ON VIS"
    on_press:
      - tc_bus_device.call:
          id: virtual_indoor_station
          address: 0