/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ModelViewer: typeof import('./.vitepress/theme/components/ModelViewer.vue')['default']
    STLLoader: typeof import('./.vitepress/theme/components/STLLoader.vue')['default']
  }
}
