# Board Setup
esp32:
  variant: esp32s3
  flash_size: 4MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
    advanced:
      execute_from_psram: true

esphome:
  platformio_options:
    board_build.flash_mode: dio

psram:
  mode: quad
  speed: 80MHz

substitutions:
  rx_pin: "GPIO9"
  tx_pin: "GPIO8"
  led_pin: "GPIO1"
  rgb_led_pin: "GPIO2"
  rgb_led_type: "ws2812"
  relay_pin: "GPIO42"
  external_button_pin: "GPIO41"
  adc_input_pin: "GPIO10"