# Configurable Options
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  log_level: "INFO"

  # Hardware Configuration
  led_pin: "GPIO1"
  rgb_led_pin: "GPIO2"
  relay_pin: "GPIO42"
  external_button_pin: "GPIO41"

globals:
  - id: intercom_serial_number
    type: int
    restore_value: true
    initial_value: '0'

  - id: second_door_station_id
    type: int
    restore_value: true
    initial_value: '99'


# Board Setup
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

# Essential ESPHome Configuration Options
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  
  min_version: "2024.8.0"

  project:
    name: "AzonInc.Doorman"
    version: "2024.9.1"

  platformio_options:
    board_build.flash_mode: dio

  on_boot:
    then:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: pulse
          red: 100%
          green: 65%
          blue: 0%
      - wait_until:
          condition:
            wifi.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: slow_pulse
          red: 0%
          green: 22%
          blue: 100%
      - wait_until:
          condition:
            api.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: none
          red: 0%
          green: 22%
          blue: 100%
          color_brightness: 60%
      - delay: 3s
      - script.execute: update_led

# Enable logging
logger:
  level: ${log_level}

api:
  reboot_timeout: 0s
  actions:
    - action: send_tc_command_raw
      variables:
        command: int
      then:
        - tc_bus.send:
            command: !lambda 'return command;'
    # TODO: Fix String to command
    - action: send_tc_command
      variables:
        type: string
        address: int
        payload: int
        serial_number: int
      then:
        - tc_bus.send:
            type: !lambda 'return string_to_command_type(type);'
            address: !lambda 'return address;'
            payload: !lambda 'return payload;'
            serial_number: !lambda 'return serial_number;'

web_server:
  version: 3
  sorting_groups:
    - id: sorting_group_doorman_settings
      name: "Doorman Settings"
      sorting_weight: 10
    - id: sorting_group_intercom_settings
      name: "TC:BUS Intercom Settings"
      sorting_weight: 20
    - id: sorting_group_sensors
      name: "Sensors"
      sorting_weight: 30
    - id: sorting_group_listeners
      name: "Command Listeners"
      sorting_weight: 31
    - id: sorting_group_controls
      name: "Controls"
      sorting_weight: 40
    - id: sorting_group_nuki
      name: "Nuki Bridge"
      sorting_weight: 50
    - id: sorting_group_system
      name: "ESPHome"
      sorting_weight: 60

ota:
  - platform: esphome
    web_server:
      sorting_group_id: sorting_group_system
  - platform: http_request
    id: ota_http_request
    web_server:
      sorting_group_id: sorting_group_system

http_request:
  verify_ssl: false

wifi:
  ap:
    ssid: "Doorman-S3 Setup"
    password: "open-sesame"

captive_portal:

# Improv for easy provisioning
improv_serial:

# Import TC:BUS Component
external_components:
  - source: github://AzonInc/Doorman@dev
    components: [ tc_bus ]
    refresh: 60s

# Setup TC:BUS Component
tc_bus:
  id: tc_bus_intercom
  event: "doorman"
  hardware_version:
    name: "Hardware"
    icon: "mdi:router-wireless"
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_sensors
  bus_command:
    id: last_bus_command
    name: "Last Bus Command"
    web_server:
      sorting_group_id: sorting_group_sensors
  serial_number_lambda: !lambda "return id(intercom_serial_number);"


switch:
  # Preconfigured Relay Switch
  - platform: gpio
    name: Relay
    icon: mdi:electric-switch
    id: doorman_relay
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
    pin: ${relay_pin}
    web_server:
      sorting_group_id: sorting_group_controls

button:
  # System Actions
  - platform: restart
    id: doorman_restart
    entity_category: CONFIG
    name: Restart
    icon: mdi:restart
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system

  - platform: safe_mode
    id: doorman_safe_mode
    name: Safe mode
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system

  - platform: factory_reset
    id: doorman_factory_reset
    name: Restore Factory Settings
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system

  # Preconfigured Open Door Button
  - platform: template
    id: open_entrance_door
    name: "Open Entrance Door"
    icon: mdi:door
    on_press:
      - tc_bus.send:
          type: open_door
          address: 0
    web_server:
      sorting_group_id: sorting_group_controls
          
  - platform: template
    id: open_second_door
    name: "Open Second Door"
    icon: mdi:door
    on_press:
      - tc_bus.send:
          type: open_door
          address: !lambda "return id(second_door_station_id);"
    web_server:
      sorting_group_id: sorting_group_controls

  - platform: template
    id: turn_on_light
    name: "Turn on the light"
    icon: mdi:lightbulb-on
    on_press:
      - tc_bus.send:
          type: light
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_controls

# Onboard Status LEDs
light:
  - platform: status_led
    id: doorman_status_led
    name: Status LED
    icon: "mdi:led-on"
    pin: ${led_pin}
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_controls

  - platform: esp32_rmt_led_strip
    id: doorman_rgb_status_led
    icon: "mdi:led-on"
    name: RGB Status LED
    internal: true
    restore_mode: ALWAYS_OFF
    rgb_order: GRB
    pin: ${rgb_led_pin}
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    gamma_correct: 1
    default_transition_length: 0ms
    effects:
      - pulse:
          name: pulse
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 0%
          max_brightness: 40%
      - pulse:
          name: slow_pulse
          transition_length: 1s
          update_interval: 2s
          min_brightness: 0%
          max_brightness: 40%
      - pulse:
          name: slow_partymode
          transition_length: 4s
          update_interval: 2s
          min_brightness: 0%
          max_brightness: 40%
    web_server:
      sorting_group_id: sorting_group_controls

sensor:
  - platform: uptime
    name: Uptime
    id: doorman_uptime
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
      ignore_strapping_warning: true
    internal: true
    id: doorman_boot_button
    name: "Flash Button"
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_sensors

  # Preconfigured Sensors
  - platform: tc_bus
    id: entrance_doorbell
    name: "Entrance Doorbell"
    type: door_call
    auto_off: 0.2s
    web_server:
      sorting_group_id: sorting_group_listeners

  - platform: tc_bus
    id: second_entrance_doorbell
    name: "Second Entrance Doorbell"
    type: door_call
    address_lambda: !lambda "return id(second_door_station_id);"
    auto_off: 0.2s
    web_server:
      sorting_group_id: sorting_group_listeners

  - platform: tc_bus
    id: apartment_doorbell
    name: "Apartment Doorbell"
    type: floor_call
    auto_off: 0.2s
    web_server:
      sorting_group_id: sorting_group_listeners

  - platform: tc_bus
    id: pick_up_phone
    name: "Pick up phone"
    type: start_talking_door_station
    address: 255
    auto_off: 0.2s
    entity_category: DIAGNOSTIC
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners

  - platform: tc_bus
    id: hang_up_phone
    name: "Hang up phone"
    type: stop_talking_door_station
    address: 255
    auto_off: 0.2s
    entity_category: DIAGNOSTIC
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners

  - platform: tc_bus
    id: function_button
    name: "Function Button"
    auto_off: 0.2s
    type: control_function
    address: 8
    entity_category: DIAGNOSTIC
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners

  - platform: tc_bus
    id: light_button
    name: "Light Button"
    type: light
    auto_off: 0.2s
    entity_category: DIAGNOSTIC
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners

  - platform: gpio
    id: doorman_external_button
    name: External Button
    icon: mdi:gesture-tap
    disabled_by_default: true
    pin:
      number: ${external_button_pin}
      mode:
        pullup: true
        input: true
      inverted: true
    web_server:
      sorting_group_id: sorting_group_sensors

script:
  - id: update_led
    then:
      - logger.log: "Conditionally set LED State"
      # TODO: Restore specific state conditionally
      # Extended by addons