# Configurable Options
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  log_level: "INFO"

  # Hardware Configuration
  led_pin: "GPIO1"
  rgb_led_pin: "GPIO2"
  relay_pin: "GPIO42"
  external_button_pin: "GPIO41"

# Board Setup
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

# Essential ESPHome Configuration Options
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  
  min_version: "2024.11.0"

  project:
    name: "AzonInc.Doorman"
    version: "2024.12.0"

  platformio_options:
    board_build.flash_mode: dio

  on_boot:
    then:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: pulse
          red: 100%
          green: 65%
          blue: 0%
      - wait_until:
          condition:
            wifi.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: slow_pulse
          red: 0%
          green: 22%
          blue: 100%
      - wait_until:
          condition:
            api.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: none
          red: 0%
          green: 22%
          blue: 100%
          color_brightness: 60%
      - delay: 3s
      - script.execute: update_led

# Enable logging
logger:
  level: ${log_level}
  logs:
    select: INFO
    number: INFO

api:
  reboot_timeout: 0s
  actions:
    - action: send_tc_command_raw
      variables:
        command: int
      then:
        - tc_bus.send:
            command: !lambda 'return command;'
    - action: send_tc_command
      variables:
        type: string
        address: int
        payload: int
        serial_number: int
      then:
        - tc_bus.send:
            type: !lambda 'return string_to_command_type(type);'
            address: !lambda 'return address;'
            payload: !lambda 'return payload;'
            serial_number: !lambda 'return serial_number;'

web_server:
  version: 3
  sorting_groups:
    - id: sorting_group_controls
      name: "Controls"
      sorting_weight: -11
    - id: sorting_group_doorman_settings
      name: "Doorman Settings"
      sorting_weight: -10
    - id: sorting_group_intercom_settings
      name: "TC:BUS Intercom Settings"
      sorting_weight: -9
    - id: sorting_group_listeners
      name: "Doorman Listeners"
      sorting_weight: -7
    - id: sorting_group_nuki
      name: "Nuki Lock"
      sorting_weight: -5
    - id: sorting_group_nuki_settings
      name: "Nuki Lock Settings"
      sorting_weight: -4
    - id: sorting_group_nuki_bridge_settings
      name: "Nuki Bridge"
      sorting_weight: -3
    - id: sorting_group_system
      name: "System"
      sorting_weight: -2

ota:
  - platform: esphome
  - platform: http_request
    id: ota_http_request

http_request:
  verify_ssl: false

update:
  - platform: http_request
    id: update_http_request_stable
    icon: "mdi:update"
    name: Firmware (stable)
    source: https://doorman.azon.ai/firmware/release/doorman-stock/manifest.json
    disabled_by_default: false
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -4

  - platform: http_request
    id: update_http_request_dev
    icon: "mdi:update"
    name: Firmware (dev)
    source: https://doorman-dev.surge.sh/firmware/release/doorman-stock/manifest.json
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -3
      
wifi:
  ap:
    ssid: "Doorman-S3 Setup"
    password: "open-sesame"

captive_portal:

# Improv for easy provisioning
improv_serial:

# Import TC:BUS Component
external_components:
  - source: github://AzonInc/Doorman@dev
    components: [ tc_bus ]
    refresh: 60s

# Setup TC:BUS Component
tc_bus:
  id: tc_bus_intercom
  event: "doorman"
  
number:
  - platform: tc_bus
    serial_number:
      id: serial_number
      name: "Serial Number"
      icon: "mdi:numeric"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -20

  - platform: template
    id: second_door_station_id
    name: "Second Door Station ID"
    mode : box
    icon: "mdi:counter"
    restore_value: true
    initial_value: '63'
    max_value: 63
    min_value: 0
    step: 1
    optimistic: true
    disabled_by_default: true
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_intercom_settings
      sorting_weight: -20

text_sensor:
  - platform: tc_bus
    hardware_version:
      id: doorman_hardware_version
      name: "Hardware"
      icon: "mdi:router-wireless"
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_system
        sorting_weight: -20
    bus_command:
      id: last_bus_command
      name: "Last Bus Command"
      web_server:
        sorting_group_id: sorting_group_listeners
        sorting_weight: -99

switch:
  # Preconfigured Relay Switch
  - platform: gpio
    name: Relay
    icon: mdi:electric-switch
    id: doorman_relay
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
    pin: ${relay_pin}
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: -7

button:
  # System Actions
  - platform: restart
    id: doorman_restart
    entity_category: CONFIG
    name: Restart
    icon: mdi:restart
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -2

  - platform: safe_mode
    id: doorman_safe_mode
    name: Safe mode
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -1

  - platform: factory_reset
    id: doorman_factory_reset
    name: Restore Factory Settings
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: 0

  # Preconfigured Open Door Button
  - platform: template
    id: open_entrance_door
    name: "Open Entrance Door"
    icon: mdi:door
    on_press:
      - tc_bus.send:
          type: open_door
          address: 0
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: -10
          
  - platform: template
    id: open_second_door
    name: "Open Second Entrance Door"
    icon: mdi:door
    on_press:
      - tc_bus.send:
          type: open_door
          address: !lambda "return id(second_door_station_id).state;"
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: -9

  - platform: template
    id: turn_on_light
    name: "Turn on the Light"
    icon: mdi:lightbulb-on
    on_press:
      - tc_bus.send:
          type: light
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_controls
      sorting_weight: -8

# Onboard Status LEDs
light:
  - platform: status_led
    id: doorman_status_led
    name: Status LED
    icon: "mdi:led-on"
    pin: ${led_pin}
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -9

  - platform: esp32_rmt_led_strip
    id: doorman_rgb_status_led
    icon: "mdi:led-on"
    name: RGB Status LED
    internal: true
    restore_mode: ALWAYS_OFF
    rgb_order: GRB
    pin: ${rgb_led_pin}
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    gamma_correct: 1
    default_transition_length: 0ms
    effects:
      - pulse:
          name: pulse
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 0%
          max_brightness: 40%
      - pulse:
          name: slow_pulse
          transition_length: 1s
          update_interval: 2s
          min_brightness: 0%
          max_brightness: 40%
      - pulse:
          name: slow_partymode
          transition_length: 4s
          update_interval: 2s
          min_brightness: 0%
          max_brightness: 40%
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -8

sensor:
  - platform: uptime
    name: Uptime
    id: doorman_uptime
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -7

  - platform: adc
    id: bus_voltage
    name: Bus Voltage
    pin: GPIO10
    update_interval: 1s
    attenuation: 12dB
    entity_category: DIAGNOSTIC
    disabled_by_default: true
    icon: "mdi:current-dc"
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -5

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
      ignore_strapping_warning: true
    internal: true
    id: doorman_boot_button
    name: "Flash Button"
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -5

  # Preconfigured Sensors
  - platform: tc_bus
    id: entrance_doorbell
    name: "Entrance Doorbell"
    type: door_call
    auto_off: 0.2s
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -28

  - platform: tc_bus
    id: second_entrance_doorbell
    name: "Second Entrance Doorbell"
    type: door_call
    address_lambda: !lambda "return id(second_door_station_id).state;"
    auto_off: 0.2s
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -27

  - platform: tc_bus
    id: apartment_doorbell
    name: "Apartment Doorbell"
    type: floor_call
    auto_off: 0.2s
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -29

  - platform: tc_bus
    id: pick_up_phone_door_call
    name: "Pick up phone (door call)"
    icon: "mdi:phone-check"
    type: start_talking_door_call
    address: 255
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -19

  - platform: tc_bus
    id: hang_up_phone_door_call
    name: "Hang up phone (door call)"
    icon: "mdi:phone-remove"
    type: stop_talking_door_call
    address: 255
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -18

  - platform: tc_bus
    id: pick_up_phone
    name: "Pick up phone"
    icon: "mdi:phone-check"
    type: start_talking
    address: 255
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -17

  - platform: tc_bus
    id: hang_up_phone
    name: "Hang up phone"
    icon: "mdi:phone-remove"
    type: stop_talking
    address: 255
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -16

  - platform: tc_bus
    id: function_button
    name: "Function Button"
    icon: "mdi:circle-outline"
    auto_off: 0.2s
    type: control_function
    payload: 255
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -6

  - platform: tc_bus
    id: light_button
    name: "Light Button"
    icon: "mdi:white-balance-sunny"
    type: light
    auto_off: 0.2s
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: -7

  - platform: gpio
    id: doorman_external_button
    name: "External Button"
    icon: "mdi:gesture-tap"
    disabled_by_default: true
    pin:
      number: ${external_button_pin}
      mode:
        pullup: true
        input: true
      inverted: true
    web_server:
      sorting_group_id: sorting_group_listeners
      sorting_weight: 99

script:
  - id: update_led
    then:
      - logger.log: "Conditionally set LED State"
      - light.turn_off:
          id: doorman_rgb_status_led
          transition_length: 1s
      # TODO: Restore specific state conditionally
      # Extended by addons