dashboard_import:
  package_import_url: github://AzonInc/doorman/firmware/examples/nuki-bridge.example.yaml@master
  import_full_config: false

packages:
  device_base: !include base.yaml
  pattern_events: !include addons/pattern-events.yaml
  ring_to_open: !include addons/ring-to-open.yaml
  memory_utils: !include addons/memory-utils.yaml
  addon_nuki_bridge: !include addons/nuki-bridge.yaml
  interactive_setup: !include addons/interactive-setup.yaml

esphome:
  project:
    name: "AzonInc.Doorman-Nuki-Bridge"

update:
  - platform: http_request
    id: update_http_request_stable
    name: Firmware (stable)
    source: https://doorman.azon.ai/firmware/release/doorman-nuki-bridge/manifest.json
    disabled_by_default: false
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -4


  - platform: http_request
    id: update_http_request_dev
    name: Firmware (dev)
    source: https://doorman-dev.surge.sh/firmware/release/doorman-nuki-bridge/manifest.json
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: -3
