dashboard_import:
  package_import_url: github://AzonInc/doorman/firmware/examples/nuki-bridge.example.yaml@master
  import_full_config: false

packages:
  device_base: !include base.yaml
  interactive_setup: !include addons/interactive-setup.yaml
  ring_to_open: !include addons/ring-to-open.yaml
  addon_nuki_bridge: !include addons/nuki-bridge.yaml

esphome:
  project:
    name: "AzonInc.Doorman-Nuki-Bridge"

esp32:
  framework:
    type: arduino
    version: 2.0.16
    platform_version: 6.7.0

update:
  - platform: http_request
    id: update_http_request_stable
    name: Firmware (stable)
    source: https://doorman.azon.ai/firmware/release/doorman-nuki-bridge/manifest.json
    disabled_by_default: false

  - platform: http_request
    id: update_http_request_dev
    name: Firmware (dev)
    source: https://doorman-dev.surge.sh/firmware/release/doorman-nuki-bridge/manifest.json
    disabled_by_default: true

# Nuki Lock Bridge
lock:
  - platform: nuki_lock
    name: Nuki Lock
    id: nuki_smart_lock

    # Required:
    is_connected: 
      id: nuki_connected
      name: "Nuki Connected"
      icon: "mdi:link"
      entity_category: DIAGNOSTIC

    is_paired:
      id: nuki_paired
      name: "Nuki Paired"
      icon: "mdi:link"
      entity_category: DIAGNOSTIC

    # Optional:
    battery_critical:
      id: nuki_battery_critical
      name: "Nuki Battery Critical"
      entity_category: DIAGNOSTIC

    battery_level:
      id: nuki_battery_level
      name: "Nuki Battery Level"
      entity_category: DIAGNOSTIC

    door_sensor:
      id: nuki_door_sensor
      name: "Nuki Door Sensor"
      disabled_by_default: true

    door_sensor_state:
      id: nuki_door_sensor_state
      name: "Nuki Door Sensor State"
      disabled_by_default: true
    
    unpair:
      id: nuki_unpair_device
      name: "Nuki Unpair Device"
      disabled_by_default: true

    pairing_mode:
      id: nuki_pairing_mode
      name: "Nuki Pairing Mode"
      disabled_by_default: true

    on_pairing_mode_on_action:
      - light.turn_on:
          id: doorman_rgb_status_led
          red: 100%
          green: 0%
          blue: 100%
          effect: pulse

    on_pairing_mode_off_action:
      - script.execute: update_led
    
    on_paired_action:
      - light.turn_on:
          id: doorman_rgb_status_led
          red: 100%
          green: 0%
          blue: 100%
          effect: none
          brightness: 60%
      - delay: 3s
      - script.execute: update_led