substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"

  # TCS Commands
  apartment_doorbell_command: "0x00000000"
  entrance_doorbell_command: "0x00000000"
  entrance_door_opener_command: "0x1100"

  # Optional Settings
  log_level: "ERROR"
  party_mode_door_opener_delay: "70ms"

dashboard_import:
  package_import_url: github://AzonInc/doorman/firmware/doorman-nuki-bridge.yaml@master
  import_full_config: false

packages:
  device_base: !include base.yaml
  addon_nuki_bridge: !include addons/nuki-bridge.yaml

esp32:
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.3.0

# Nuki Lock Bridge
lock:
  - platform: nuki_lock
    name: Nuki Lock
    id: nuki_smart_lock

    # Required:
    is_connected: 
      name: "Nuki Connected"

    is_paired:
      id: nuki_paired
      name: "Nuki Paired"
      icon: "mdi:link"

    # Optional:
    battery_critical:
      name: "Nuki Battery Critical"

    battery_level:
      name: "Nuki Battery Level"

    door_sensor:
      name: "Nuki Door Sensor"
      disabled_by_default: true

    door_sensor_state:
      name: "Nuki Door Sensor State"
      disabled_by_default: true
    
    unpair:
      name: "Unpair Nuki Device"
      disabled_by_default: true

    pairing_mode:
      name: "Nuki Pairing Mode"
      disabled_by_default: true

    on_pairing_mode_on_action:
      - light.turn_on:
          id: doorman_rgb_status_led
          red: 100%
          green: 0%
          blue: 100%
          effect: pulse
          brightness: 60%

    on_pairing_mode_off_action:
      - light.turn_off:
          id: doorman_rgb_status_led
    
    on_paired_action:
      - light.turn_on:
          id: doorman_rgb_status_led
          red: 100%
          green: 0%
          blue: 100%
          brightness: 60%
      - delay: 3s
      - light.turn_off:
          id: doorman_rgb_status_led