dashboard_import:
  package_import_url: github://AzonInc/doorman/firmware/examples/doorman-stock.yaml@master
  import_full_config: true

packages:
  device_base: !include base.yaml

esphome:
  project:
    name: "AzonInc.Doorman-Stock"

esp32_improv:
  authorizer: none

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://doorman.azon.ai/firmware/release/doorman-stock-manifest.json