substitutions:
  update_url_stable: "https://doorman.azon.ai/firmware/release/doorman-nuki-bridge/manifest.json"
  update_url_dev: "https://doorman-dev.surge.sh/firmware/release/doorman-nuki-bridge/manifest.json"

dashboard_import:
  package_import_url: github://azoninc/doorman/firmware/examples/ha-nuki-bridge.example.yaml
  import_full_config: true

packages:
  host: !include host/esp32-s3-oct.yaml
  base: !include base.yaml
  homeassistant: !include addons/homeassistant.yaml
  pattern_events: !include addons/pattern-events.yaml
  ring_to_open: !include addons/ring-to-open.yaml
  intercom_settings: !include addons/intercom-settings.yaml
  addon_nuki_bridge: !include addons/nuki-bridge.yaml
  interactive_setup: !include addons/interactive-setup.yaml

esphome:
  project:
    name: "AzonInc.Doorman-Nuki-Bridge"