dashboard_import:
  package_import_url: github://AzonInc/doorman/firmware/examples/ha-nuki-bridge.example.yaml@master
  import_full_config: false

packages:
  device_base: !include base.yaml
  homeassistant: !include addons/homeassistant.yaml
  pattern_events: !include addons/pattern-events.yaml
  ring_to_open: !include addons/ring-to-open.yaml
  intercom_settings: !include addons/intercom-settings.yaml
  addon_nuki_bridge: !include addons/nuki-bridge.yaml
  interactive_setup: !include addons/interactive-setup.yaml

esphome:
  project:
    name: "AzonInc.Doorman-Nuki-Bridge"

esp32:
  framework:
    type: arduino
    version: 2.0.16
    platform_version: 6.7.0