packages:
  host: !include host/esp32-s3-oct.yaml
  base: !include base.yaml
  mqtt: !include addons/mqtt.yaml
  pattern_events: !include addons/pattern-events.yaml
  ring_to_open: !include addons/ring-to-open.yaml
  intercom_settings: !include addons/intercom-settings.yaml
  addon_nuki_bridge: !include addons/nuki-bridge.yaml
  interactive_setup: !include addons/interactive-setup.yaml

esphome:
  project:
    name: "AzonInc.Doorman-Nuki-Bridge"