name: Nightly Firmware Build Check
on:
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Doorman Stock for Home Assistant (ESP32-S3) Firmware
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: firmware/ha-doorman-stock.yaml
          version: latest
          complete-manifest: true

      - name: Build Doorman Nuki Bridge for Home Assistant (ESP32-S3) Firmware
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: firmware/ha-doorman-nuki-bridge.yaml
          version: latest
          complete-manifest: true

      - name: Build Component Test (ESP8266) Firmware
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: firmware/tc-bus-component-8266.yaml
          version: latest

      - name: Send Discord failure notification
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#FF6961"
          message: "Doorman Firmware: Nightly build failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"