name: Build Vitepress Docs

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Extract version from base.yaml
        run: |
          VERSION=$(awk '/project:/, /version:/' firmware/base.yaml | grep 'version:' | awk '{print $2}' | sed 's/[",]//g')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
      - name: Update package.json version
        if: github.ref == 'refs/heads/master'
        working-directory: docs
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION}\"/" package.json

      - name: Update package.json version
        if: github.ref != 'refs/heads/master'
        working-directory: docs
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION}-dev\"/" package.json
          
      - name: Update example fw branch
        if: github.ref != 'refs/heads/master'
        working-directory: firmware/examples
        run: |
          sed -i 's/@master/@dev/g' *.example.yaml

      - name: Update docs branch
        if: github.ref != 'refs/heads/master'
        working-directory: docs
        run: |
          sed -i 's/@master/@dev/g' *.md
          sed -i 's/\/master\//\/dev\//g' *.md
          sed -i 's/@master/@dev/g' *.yaml

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build with VitePress
        working-directory: docs
        run: npm run build

      - name: Build Lunaria Dashboard
        working-directory: docs
        run: npm run lunaria:build

      - name: Upload VitePress artifact
        uses: actions/upload-artifact@v4
        with:
          name: vitepress-docs
          path: docs/.vitepress/dist