name: Nightly Firmware Build Check
on:
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Compile Stock Firmware
        uses: esphome/build-action@v4.0.1
        with:
          yaml_file: firmware/doorman-stock.yaml
          version: beta

      - name: Compile Nuki Bridge Firmware
        uses: esphome/build-action@v4.0.1
        with:
          yaml_file: firmware/doorman-nuki-bridge.yaml
          version: beta

      - name: Send Discord failure notification
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#FF6961"
          message: "The latest nightly build failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"