name: Build Stock Firmware
on:
  release:
    types: [created]

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install ESPHome
        run: pip install --user esphome
      
      - name: Compile Release Firmware
        working-directory: firmware
        run: |
          esphome compile doorman-stock.yaml
          mkdir -p bin
          cp .esphome/build/doorman-s3/.pioenvs/doorman-s3/firmware.factory.bin bin/firmware-factory.bin
          cp .esphome/build/doorman-s3/.pioenvs/doorman-s3/firmware.bin bin/stock-firmware.bin

      - name: Compile Nuki Bridge Firmware
        working-directory: firmware
        run: |
          rm -rf .esphome/build/doorman-s3
          esphome compile doorman-nuki-bridge.yaml
          mkdir -p bin
          cp .esphome/build/doorman-s3/.pioenvs/doorman-s3/firmware.factory.bin bin/nuki-bridge-firmware-factory.bin
          cp .esphome/build/doorman-s3/.pioenvs/doorman-s3/firmware.bin bin/nuki-bridge-firmware.bin

      - name: Upload Firmware
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "firmware/bin/*.bin"