name: Bundle build assets

on:
  workflow_call:

jobs:
  bundle-assets:
    name: Create asset bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Output Directories
        run: |
          mkdir -p output/firmware/release
          mkdir -p output/firmware/temp

      - name: Download VitePress docs
        uses: actions/download-artifact@v8
        with:
          name: vitepress-docs
          path: output

      - name: Copy interactive BOMs
        run: |
          cp hardware/core_board/bom/ibom.html output/core_board_ibom.html
          cp hardware/extension_audio/bom/ibom.html output/extension_audio_ibom.html

      - name: Download Webserver Bundle
        uses: actions/download-artifact@v8
        with:
          name: webserver-bundle
          path: output/firmware/esphome-webserver
        
      - name: Download all firmware artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: firmware.*
          path: output/firmware/release
          merge-multiple: true

      # Temporary duplicate for stock compatibility
      - name: Temporary backwards compatibility for stock firmware filenames
        working-directory: output/firmware/release
        run: |
          for f in *.standard; do cp -r "$f" "${f%.standard}.stock"; done

      - name: Upload Pages artifact
        if: github.ref_name == 'master'
        uses: actions/upload-pages-artifact@v5
        with:
          path: output
      
      - name: Upload Assets Bundle
        if: github.ref_name != 'master'
        uses: actions/upload-artifact@v7
        with:
          name: asset-bundle
          path: output