# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy Docs and ESPHome Firmware to Pages

on:
  workflow_dispatch:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build Vitepress Docs
  build-docs:
    name: Build Docs
    uses: ./.github/workflows/build-docs.yml

  prepare-release:
    runs-on: ubuntu-latest
    name: Prepare release data
    outputs:
      release_summary: ${{ steps.generate-summary.outputs.summary }}
      release_url: ${{ steps.generate-summary.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Data
        id: generate-summary
        run: |
          GITHUB_REF_NAME=${{ github.ref_name }}
          SHA=${{ github.sha }}

          URL="https://doorman.azon.ai/changelog/firmware"

          if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            SUMMARY="Please review the release notes before updating, as some breaking changes might be present."
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            SUMMARY="This is an experimental update that should be mostly stable but may still have some minor unstable features. Details: $(git log -1 --pretty=%B), ${SHA}"
            URL="https://doorman-dev.surge.sh/changelog/firmware"
          elif [[ "${GITHUB_REF_NAME}" == dev* ]]; then
            SUMMARY="WARNING! This is an experimental update (${GITHUB_REF_NAME}) with unstable features. Proceed with the update only if explicitly instructed by the developers. Details: $(git log -1 --pretty=%B), ${SHA}"
            URL="https://doorman-dev.surge.sh/changelog/firmware"
          else
            SUMMARY=""
          fi

          # Encode special characters
          SUMMARY="${SUMMARY//'%'/'%25'}"
          SUMMARY="${SUMMARY//$'\n'/'%0A'}"
          SUMMARY="${SUMMARY//$'\r'/'%0D'}"
  
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "summary=$SUMMARY" >> $GITHUB_OUTPUT

  # Build stable firmware
  build-esp32-stock-stable-firmware:
    if: github.ref_name == 'master'
    name: Build ESP32 Stock Firmware (Home Assistant, stable)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32.ha.stock.yaml
      name: AzonInc.Doorman
      esphome_version: latest
      directory_name: esp32.ha.stock
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-s3-stock-stable-firmware:
    if: github.ref_name == 'master'
    name: Build ESP32-S3 Stock Firmware (Home Assistant, stable)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32-s3.ha.stock.yaml
      name: AzonInc.Doorman
      esphome_version: latest
      directory_name: esp32-s3.ha.stock
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-s3-oct-stock-stable-firmware:
    if: github.ref_name == 'master'
    name: Build ESP32-S3-OCT Stock Firmware (Home Assistant, stable)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32-s3-oct.ha.stock.yaml
      name: AzonInc.Doorman
      esphome_version: latest
      directory_name: esp32-s3-oct.ha.stock
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp8266-stock-stable-firmware:
    if: github.ref_name == 'master'
    name: Build ESP8266 Stock Firmware (Home Assistant, stable)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp8266.ha.stock.yaml
      name: AzonInc.Doorman
      esphome_version: latest
      directory_name: esp8266.ha.stock
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-nuki-bridge-stable-firmware:
    if: github.ref_name == 'master'
    name: Build ESP32 Nuki Bridge Firmware (Home Assistant, stable)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32.ha.nuki-bridge.yaml
      name: AzonInc.Doorman-Nuki-Bridge
      esphome_version: latest
      directory_name: esp32.ha.nuki-bridge
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-s3-nuki-bridge-stable-firmware:
    if: github.ref_name == 'master'
    name: Build ESP32-S3 Nuki Bridge Firmware (Home Assistant, stable)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32-s3.ha.nuki-bridge.yaml
      name: AzonInc.Doorman-Nuki-Bridge
      esphome_version: latest
      directory_name: esp32-s3.ha.nuki-bridge
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-s3-oct-nuki-bridge-stable-firmware:
    if: github.ref_name == 'master'
    name: Build ESP32-S3-OCT Nuki Bridge Firmware (Home Assistant, stable)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32-s3-oct.ha.nuki-bridge.yaml
      name: AzonInc.Doorman-Nuki-Bridge
      esphome_version: latest
      directory_name: esp32-s3-oct.ha.nuki-bridge
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}


  # Build dev firmware
  build-esp32-stock-dev-firmware:
    if: startsWith(github.ref_name, 'dev')
    name: Build ESP32 Stock Firmware (Home Assistant, dev)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32.ha.stock.dev.yaml
      name: AzonInc.Doorman
      esphome_version: dev
      directory_name: esp32.ha.stock
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-s3-stock-dev-firmware:
    if: startsWith(github.ref_name, 'dev')
    name: Build ESP32-S3 Stock Firmware (Home Assistant, dev)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32-s3.ha.stock.dev.yaml
      name: AzonInc.Doorman
      esphome_version: dev
      directory_name: esp32-s3.ha.stock
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-s3-oct-stock-dev-firmware:
    if: startsWith(github.ref_name, 'dev')
    name: Build ESP32-S3-OCT Stock Firmware (Home Assistant, dev)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32-s3-oct.ha.stock.dev.yaml
      name: AzonInc.Doorman
      esphome_version: dev
      directory_name: esp32-s3-oct.ha.stock
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp8266-stock-dev-firmware:
    if: startsWith(github.ref_name, 'dev')
    name: Build ESP8266 Stock Firmware (Home Assistant, dev)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp8266.ha.stock.dev.yaml
      name: AzonInc.Doorman
      esphome_version: dev
      directory_name: esp8266.ha.stock
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-nuki-bridge-dev-firmware:
    if: startsWith(github.ref_name, 'dev')
    name: Build ESP32 Nuki Bridge Firmware (Home Assistant, dev)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32.ha.nuki-bridge.dev.yaml
      name: AzonInc.Doorman-Nuki-Bridge
      esphome_version: dev
      directory_name: esp32.ha.nuki-bridge
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-s3-nuki-bridge-dev-firmware:
    if: startsWith(github.ref_name, 'dev')
    name: Build ESP32-S3 Nuki Bridge Firmware (Home Assistant, dev)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32-s3.ha.nuki-bridge.dev.yaml
      name: AzonInc.Doorman-Nuki-Bridge
      esphome_version: dev
      directory_name: esp32-s3.ha.nuki-bridge
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}

  build-esp32-s3-oct-nuki-bridge-dev-firmware:
    if: startsWith(github.ref_name, 'dev')
    name: Build ESP32-S3-OCT Nuki Bridge Firmware (Home Assistant, dev)
    uses: ./.github/workflows/build-esphome.yml
    needs: prepare-release
    with:
      files: firmware/configurations/esp32-s3-oct.ha.nuki-bridge.dev.yaml
      name: AzonInc.Doorman-Nuki-Bridge
      esphome_version: dev
      directory_name: esp32-s3-oct.ha.nuki-bridge
      summary: ${{ needs.prepare-release.outputs.release_summary }}
      url: ${{ needs.prepare-release.outputs.release_url }}
          
  # Bundle all assets for Pages
  bundle-assets-stable:
    if: github.ref_name == 'master'
    name: Create asset bundle (stable)
    uses: ./.github/workflows/bundle-assets.yml
    needs: [build-docs, build-esp8266-stock-stable-firmware, build-esp32-stock-stable-firmware, build-esp32-s3-stock-stable-firmware, build-esp32-s3-oct-stock-stable-firmware, build-esp32-nuki-bridge-stable-firmware, build-esp32-s3-nuki-bridge-stable-firmware, build-esp32-s3-oct-nuki-bridge-stable-firmware]

  bundle-assets-dev:
    if: startsWith(github.ref_name, 'dev')
    name: Create asset bundle (dev)
    uses: ./.github/workflows/bundle-assets.yml
    needs: [build-docs, build-esp8266-stock-dev-firmware, build-esp32-stock-dev-firmware, build-esp32-s3-stock-dev-firmware, build-esp32-s3-oct-stock-dev-firmware, build-esp32-nuki-bridge-dev-firmware, build-esp32-s3-nuki-bridge-dev-firmware, build-esp32-s3-oct-nuki-bridge-dev-firmware]


  # Deployment job
  deploy-stable:
    if: github.ref_name == 'master'
    name: Deploy to Github Pages (stable)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [bundle-assets-stable]
    runs-on: ubuntu-latest 
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-dev:
    if: startsWith(github.ref_name, 'dev')
    name: Deploy to surge.sh (dev)
    environment:
      name: surge.sh
      url: "https://doorman-dev.surge.sh/"
    needs: [bundle-assets-dev]
    runs-on: ubuntu-latest
    steps:
      - name: Download Assets
        uses: actions/download-artifact@v4
        with:
          name: asset-bundle
          path: output

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g surge
      - run: surge output ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}